/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

export default function DiscoBall(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('/glb/disco-ball-draco-v1.glb');
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    if (actions) {
      actions['Take 001'].play();
    }
  }, [actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, 0, 0]}>
        <mesh castShadow receiveShadow geometry={nodes.pSphere3_disco_mat_0.geometry} material={materials.disco_mat} />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pSphere3_non_disco_mat_0.geometry}
          material={materials.non_disco_mat}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/glb/disco-ball-draco-v1.glb');
