/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useMemo, useRef, useState } from 'react';
import { useGLTF, useAnimations, useHelper } from '@react-three/drei';
import { AxesHelper } from 'three';

export default function MarcelloAnimated(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('/glb/marcello/marcello-idle-gangnam.glb');
  const { actions } = useAnimations(animations, group);
  const [actionIndex, setActionIndex] = useState(0);
  const actionNames = useMemo(() => ['mixamo.com', 'GangnamStyle'], []);

  useHelper(group, AxesHelper, 5, '#ff0000', '#00ff00', '#0000ff');
  // axisHelper.setColors('#ff0000', '#00ff00', '#0000ff');

  // Idle, ArmStretching, HipHopDance
  useEffect(() => {
    if (actions) {
      actions[actionNames[actionIndex]].play();
    }
  }, [actions, actionIndex, actionNames]);

  useEffect(() => {
    if (props.dance) {
      setActionIndex(1);
      actions[actionNames[1]].play();
    }
  }, [props.dance, actions, actionIndex, actionNames]);

  return (
    <group ref={group} {...props} dispose={null} scale={[2, 2, 2]}>
      <group
        position={[0, -0.92, -0.04]}
      >
        <primitive object={nodes.mixamorigHips} />
        <skinnedMesh
          castShadow
          receiveShadow
          geometry={nodes.EyeLeft.geometry}
          material={nodes.EyeLeft.material}
          skeleton={nodes.EyeLeft.skeleton}
        />
        <skinnedMesh
          castShadow
          receiveShadow
          geometry={nodes.EyeRight.geometry}
          material={nodes.EyeRight.material}
          skeleton={nodes.EyeRight.skeleton}
        />
        <skinnedMesh
          castShadow
          receiveShadow
          geometry={nodes.Wolf3D_Body.geometry}
          material={materials.Material_2}
          skeleton={nodes.Wolf3D_Body.skeleton}
        />
        <skinnedMesh
          castShadow
          receiveShadow
          geometry={nodes.Wolf3D_Head.geometry}
          material={materials.Material_3}
          skeleton={nodes.Wolf3D_Head.skeleton}
        />
        <skinnedMesh
          castShadow
          receiveShadow
          geometry={nodes.Wolf3D_Outfit_Bottom.geometry}
          material={materials.Material_4}
          skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton}
        />
        <skinnedMesh
          castShadow
          receiveShadow
          geometry={nodes.Wolf3D_Outfit_Footwear.geometry}
          material={materials.Material_5}
          skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton}
        />
        <skinnedMesh
          castShadow
          receiveShadow
          geometry={nodes.Wolf3D_Outfit_Top.geometry}
          material={materials.Material_6}
          skeleton={nodes.Wolf3D_Outfit_Top.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Wolf3D_Teeth.geometry}
          material={materials.Material_7}
          skeleton={nodes.Wolf3D_Teeth.skeleton}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/glb/marcello/marcello-idle-gangnam.glb');
