/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

export default function MarcelloIntro(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('/glb/marcello/marcello-anim-full-skinned.glb');
  const { actions } = useAnimations(animations, group);

  const actionIndex = useRef(0);

  const changeAction = () => {
    console.log('clicked');
    actionIndex.current += 1;
    if (actionIndex >= actions.length) {
      actionIndex.current = 0;
    }
  };

  // Idle, ArmStretching, HipHopDance
  useEffect(() => {
    if (actions) {
      const actionNames = ['mixamo.com', 'ArmStretching', 'HipHopDance'];
      actions[actionNames[actionIndex.current]].play();
    }
  }, [actions]);

  return (
    <group ref={group} {...props} dispose={null} scale={[2, 2, 2]}>
      <group position={[0, -0.92, -0.04]} onClick={() => changeAction()}>
        <primitive object={nodes.mixamorigHips} />
        <skinnedMesh
          geometry={nodes.EyeLeft.geometry}
          material={nodes.EyeLeft.material}
          skeleton={nodes.EyeLeft.skeleton}
        />
        <skinnedMesh
          geometry={nodes.EyeRight.geometry}
          material={nodes.EyeRight.material}
          skeleton={nodes.EyeRight.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Wolf3D_Body.geometry}
          material={materials.Material_0}
          skeleton={nodes.Wolf3D_Body.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Wolf3D_Head.geometry}
          material={materials.Material_1}
          skeleton={nodes.Wolf3D_Head.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Wolf3D_Outfit_Bottom.geometry}
          material={materials.Material_2}
          skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Wolf3D_Outfit_Footwear.geometry}
          material={materials.Material_3}
          skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Wolf3D_Outfit_Top.geometry}
          material={materials.Material_4}
          skeleton={nodes.Wolf3D_Outfit_Top.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Wolf3D_Teeth.geometry}
          material={materials.Material_5}
          skeleton={nodes.Wolf3D_Teeth.skeleton}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/glb/marcello/marcello-anim-full-skinned.glb');
