/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useMemo, useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';
import { GLTF } from 'three-stdlib'
import * as THREE from 'three'

type GLTFResult = GLTF & {
  nodes: {
    EyeLeft: THREE.SkinnedMesh
    EyeRight: THREE.SkinnedMesh
    Wolf3D_Body: THREE.SkinnedMesh
    Wolf3D_Head: THREE.SkinnedMesh
    Wolf3D_Outfit_Bottom: THREE.SkinnedMesh
    Wolf3D_Outfit_Footwear: THREE.SkinnedMesh
    Wolf3D_Outfit_Top: THREE.SkinnedMesh
    Wolf3D_Teeth: THREE.SkinnedMesh
    mixamorigHips: THREE.Bone
  }
  materials: {
    Material_0: THREE.MeshStandardMaterial
    Material_2: THREE.MeshStandardMaterial
    Material_3: THREE.MeshStandardMaterial
    Material_4: THREE.MeshStandardMaterial
    Material_5: THREE.MeshStandardMaterial
    Material_6: THREE.MeshStandardMaterial
    Material_7: THREE.MeshStandardMaterial
  }
}
type ActionName = 'GangnamStyle' | 'mixamo.com'
type GLTFActions = Record<ActionName, THREE.AnimationAction>


export default function MarcelloAnimated({ ...props }:JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF('/marcello-idle-gangnam-draco-v1.glb') as GLTFResult
  const { actions } = useAnimations<GLTFActions>(animations, group)
  const actionNames = useMemo(() => ['mixamo.com', 'GangnamStyle'], []);

  useEffect(() => {
    if (props.dance) {
      actions[actionNames[1]].play();
    }
  }, [props.dance, actions, actionNames]);

  return (
    <group ref={group} {...props} dispose={null} scale={[1,1,1]}>
      <group
        // position={[0, -1.92, -0.04]}
      >
        <primitive object={nodes.mixamorigHips} />
        <skinnedMesh
          castShadow
          receiveShadow
          geometry={nodes.EyeLeft.geometry}
          material={nodes.EyeLeft.material}
          skeleton={nodes.EyeLeft.skeleton}
        />
        <skinnedMesh
          castShadow
          receiveShadow
          geometry={nodes.EyeRight.geometry}
          material={nodes.EyeRight.material}
          skeleton={nodes.EyeRight.skeleton}
        />
        <skinnedMesh
          castShadow
          receiveShadow
          geometry={nodes.Wolf3D_Body.geometry}
          material={materials.Material_2}
          skeleton={nodes.Wolf3D_Body.skeleton}
        />
        <skinnedMesh
          castShadow
          receiveShadow
          geometry={nodes.Wolf3D_Head.geometry}
          material={materials.Material_3}
          skeleton={nodes.Wolf3D_Head.skeleton}
        />
        <skinnedMesh
          castShadow
          receiveShadow
          geometry={nodes.Wolf3D_Outfit_Bottom.geometry}
          material={materials.Material_4}
          skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton}
        />
        <skinnedMesh
          castShadow
          receiveShadow
          geometry={nodes.Wolf3D_Outfit_Footwear.geometry}
          material={materials.Material_5}
          skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton}
        />
        <skinnedMesh
          castShadow
          receiveShadow
          geometry={nodes.Wolf3D_Outfit_Top.geometry}
          material={materials.Material_6}
          skeleton={nodes.Wolf3D_Outfit_Top.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Wolf3D_Teeth.geometry}
          material={materials.Material_7}
          skeleton={nodes.Wolf3D_Teeth.skeleton}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/glb/marcello/marcello-idle-gangnam-draco-v1.glb');
