/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function QuillSamurai(props) {
  const group = useRef();
  const { nodes } = useGLTF('/glb/japan/Quill-Samurai.gltf');

  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[-0.33, 0.08, 1.45]} rotation={[-0.01, 0.01, -0.07]} scale={[1.17, 1.17, 1.17]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Background__0.geometry}
          material={nodes.Background__0.material}
        />
        <mesh castShadow receiveShadow geometry={nodes.clouds__0.geometry} material={nodes.clouds__0.material} />
        <mesh castShadow receiveShadow geometry={nodes.NewLayer0__0.geometry} material={nodes.NewLayer0__0.material} />
        <mesh castShadow receiveShadow geometry={nodes.Pedals__0.geometry} material={nodes.Pedals__0.material} />
        <mesh castShadow receiveShadow geometry={nodes.Samurai__0.geometry} material={nodes.Samurai__0.material} />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Samurai__0001.geometry}
          material={nodes.Samurai__0001.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Samurai__0002.geometry}
          material={nodes.Samurai__0002.material}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/glb/japan/Quill-Samurai.gltf');
