/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from 'react';
// import { useGLTF } from '@react-three/drei';
import { useLoader } from '@react-three/fiber';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader';

export default function Sensoji(props) {
  // const group = useRef();
  // const { nodes, materials } = useGLTF('/FM-Polygon-JP-Sensoji-3.glb')
  const { scene } = useLoader(GLTFLoader, '/glb/japan/FM-Polygon-JP-Sensoji-3.glb');

  return <primitive object={scene} position={[0, 2, 0]} />;
}

useLoader.preload(GLTFLoader, '/glb/japan/FM-Polygon-JP-Sensoji-3.glb');
// useGLTF.preload('/glb/japan/FM-Polygon-JP-Sensoji-3.glb');
