/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/glb/sci-fi/star-destroyer.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, 0, -0.58]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_11002.geometry}
          material={materials['initialShadingGroup.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_3002.geometry}
          material={nodes.Mesh_3002.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_4002.geometry}
          material={nodes.Mesh_4002.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_0002.geometry}
          material={nodes.Mesh_0002.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_6002.geometry}
          material={nodes.Mesh_6002.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_1002.geometry}
          material={materials.blinn7SG}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_10002.geometry}
          material={materials.blinn8SG}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_2002.geometry}
          material={materials['blinn9SG.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_5002.geometry}
          material={materials.blinn12SG}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_7002.geometry}
          material={materials.blinn2SG}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_8002.geometry}
          material={materials['blinn5SG.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_9002.geometry}
          material={materials['blinn6SG.001']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/glb/sci-fi/star-destroyer.glb');
