/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useEffect, useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ground_lambert9_0: THREE.Mesh
    Object_11: THREE.SkinnedMesh
    Object_7: THREE.SkinnedMesh
    Object_8: THREE.SkinnedMesh
    Object_9: THREE.SkinnedMesh
    Cube: THREE.Mesh
    _rootJoint: THREE.Bone
  }
  materials: {
    lambert9: THREE.MeshBasicMaterial
    outline_mat: THREE.MeshBasicMaterial
    maya_eye_mat: THREE.MeshBasicMaterial
    maya_body_mat: THREE.MeshBasicMaterial
    maya_moustaches_mat: THREE.MeshBasicMaterial
    Material: THREE.MeshStandardMaterial
  }
}

type ActionName = 'BeingCute'
type GLTFActions = Record<ActionName, THREE.AnimationAction>

export default function Tati(props) {
  const group = useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF('/maya-birmain-cat-draco-v2-512.glb') as GLTFResult
  const { actions } = useAnimations<GLTFActions>(animations, group)

  useEffect(() => {
    actions?.BeingCute.play();
  });

  return (
    <group ref={group} {...props} dispose={null} scale={[0.025, 0.025, 0.025]}>
      <primitive object={nodes._rootJoint} />
      {/*<group position={[44.48, 0.11, -37.6]} scale={[159.47, 159.47, 159.47]}>*/}
      {/*  <mesh castShadow receiveShadow geometry={nodes.ground_lambert9_0.geometry} material={materials.lambert9} />*/}
      {/*</group>*/}
      <skinnedMesh
        castShadow
        receiveShadow
        geometry={nodes.Object_11.geometry}
        material={materials.outline_mat}
        skeleton={nodes.Object_11.skeleton}
      />
      <skinnedMesh
        castShadow
        receiveShadow
        geometry={nodes.Object_7.geometry}
        material={materials.maya_eye_mat}
        skeleton={nodes.Object_7.skeleton}
      />
      <skinnedMesh
        castShadow
        receiveShadow
        geometry={nodes.Object_8.geometry}
        material={materials.maya_body_mat}
        skeleton={nodes.Object_8.skeleton}
      />
      <skinnedMesh
        castShadow
        receiveShadow
        geometry={nodes.Object_9.geometry}
        material={materials.maya_moustaches_mat}
        skeleton={nodes.Object_9.skeleton}
      />
      <mesh castShadow receiveShadow geometry={nodes.Cube.geometry} material={materials.Material} />
    </group>
  );
}

useGLTF.preload('/glb/maya-birmain-cat-draco-v2-512.glb');
