/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Tattooine(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF('/glb/sci-fi/tattooine.glb');
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tatooine.geometry}
        material={materials['Material.001']}
        rotation={[2.46, 0.97, 1.62]}
      />
    </group>
  );
}

useGLTF.preload('/glb/sci-fi/tattooine.glb');
