/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function TheRiver(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/glb/nature/the-river.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube069.geometry}
        material={nodes.Cube069.material}
        position={[-7.44, -1.76, -0.69]}
        rotation={[0.07, -0.05, -2.1]}
        scale={[0.52, 0.52, 0.52]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube045.geometry}
        material={nodes.Cube045.material}
        position={[-1.01, -1.73, -7.31]}
        rotation={[-1.63, -0.16, 1.38]}
        scale={[0.51, 0.51, 0.51]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube044.geometry}
        material={nodes.Cube044.material}
        position={[0.22, -3.3, -6.79]}
        rotation={[-1.4, 0.04, -2.74]}
        scale={[0.29, 0.29, 0.29]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube043.geometry}
        material={nodes.Cube043.material}
        position={[-5.08, -3.71, -6.17]}
        rotation={[-0.32, -1.13, 2.77]}
        scale={[0.39, 0.39, 0.39]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube042.geometry}
        material={nodes.Cube042.material}
        position={[5.41, -1.31, 6.9]}
        scale={[0.35, 0.35, 0.35]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere002.geometry}
        material={nodes.Icosphere002.material}
        position={[6.85, -1.86, 2.71]}
        rotation={[2.93, -0.85, 2.85]}
        scale={[0.83, 0.83, 0.83]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube027.geometry}
        material={nodes.Cube027.material}
        position={[6.19, -1.4, -6.12]}
        rotation={[2.29, 0.5, -1.89]}
        scale={[0.69, 0.69, 0.69]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube026.geometry}
        material={nodes.Cube026.material}
        position={[-5.56, -3.29, -5.71]}
        rotation={[0.77, 0.34, 0.43]}
        scale={[0.51, 0.51, 0.51]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere001.geometry}
        material={nodes.Icosphere001.material}
        position={[6.86, -3.04, -1.05]}
        rotation={[-1.34, 0.26, 2.66]}
        scale={[0.56, 0.56, 0.56]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere000.geometry}
        material={nodes.Icosphere000.material}
        position={[6.92, -3.5, -2.04]}
        rotation={[-1.71, -0.32, -0.17]}
        scale={[0.6, 0.6, 0.6]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube025.geometry}
        material={nodes.Cube025.material}
        position={[-6.7, -3.59, 2.25]}
        rotation={[-0.12, 0.14, -2.71]}
        scale={[0.51, 0.51, 0.51]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube006.geometry}
        material={nodes.Cube006.material}
        position={[-7.58, -1.94, 0.49]}
        rotation={[1.13, 0.24, 0.38]}
        scale={[0.28, 0.28, 0.28]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005.geometry}
        material={nodes.Cube005.material}
        position={[-0.19, -3.43, 6.85]}
        rotation={[2.92, -0.43, 0.78]}
        scale={[0.31, 0.31, 0.31]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube004.geometry}
        material={nodes.Cube004.material}
        position={[-1.27, -3.38, 6.51]}
        rotation={[-1.7, -0.38, -1.88]}
        scale={[0.67, 0.67, 0.67]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube003.geometry}
        material={materials.Material}
        position={[0.15, -3.38, 0.72]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.91, 0.91, 0.91]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002.geometry}
        material={materials.TERRE}
        position={[-0.8, -1.53, 0.16]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube068.geometry}
        material={nodes.Cube068.material}
        position={[-5.82, 0, -0.82]}
        rotation={[-Math.PI, 0.88, -Math.PI]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube061.geometry}
        material={nodes.Cube061.material}
        position={[-5.29, 0.01, 0.77]}
        rotation={[-Math.PI, 0.16, -Math.PI]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube058.geometry}
        material={nodes.Cube058.material}
        position={[1.46, 0.02, -1.82]}
        rotation={[-Math.PI, 0.15, -Math.PI]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder044.geometry}
        material={nodes.Cylinder044.material}
        position={[-2.56, 0.22, 4.05]}
        rotation={[-Math.PI, 0.71, -Math.PI]}
        scale={[0.02, 0.05, 0.04]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder043.geometry}
        material={nodes.Cylinder043.material}
        position={[0.31, 0.91, -2.21]}
        rotation={[-0.07, -0.01, -0.07]}
        scale={[0.08, 0.08, 0.08]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder038.geometry}
        material={nodes.Cylinder038.material}
        position={[5.01, 0.79, -4.14]}
        rotation={[0, 0, 0.05]}
        scale={[0.08, 0.08, 0.08]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder046.geometry}
        material={nodes.Cylinder046.material}
        position={[-5.9, 1.05, 4.73]}
        rotation={[0.21, -0.03, -0.06]}
        scale={[0.08, 0.08, 0.08]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder045.geometry}
        material={nodes.Cylinder045.material}
        position={[-2.52, 0.24, 3.97]}
        rotation={[-0.02, -0.04, -0.12]}
        scale={[0.08, 0.08, 0.08]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder037.geometry}
        material={nodes.Cylinder037.material}
        position={[2.5, 0.57, 1.71]}
        rotation={[3.08, 0.2, 3.14]}
        scale={[0.08, 0.08, 0.08]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder033.geometry}
        material={nodes.Cylinder033.material}
        position={[5.05, -0.14, -2.49]}
        rotation={[Math.PI, -1.24, Math.PI]}
        scale={[0.19, 0.19, 0.19]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder032.geometry}
        material={nodes.Cylinder032.material}
        position={[4.82, -0.14, -1.82]}
        rotation={[0, -1.1, 0]}
        scale={[0.1, 0.1, 0.1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder031.geometry}
        material={nodes.Cylinder031.material}
        position={[5.48, -0.1, -1.54]}
        rotation={[0, -0.12, 0]}
        scale={[0.12, 0.12, 0.12]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder030.geometry}
        material={nodes.Cylinder030.material}
        position={[4.73, -0.14, -2.21]}
        rotation={[0, 1.36, 0]}
        scale={[0.22, 0.22, 0.22]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder029.geometry}
        material={nodes.Cylinder029.material}
        position={[5.03, -0.13, -1.52]}
        rotation={[0, 1.36, 0]}
        scale={[0.21, 0.21, 0.21]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder028.geometry}
        material={nodes.Cylinder028.material}
        position={[5.17, -0.14, -2.04]}
        rotation={[0, 1.36, 0]}
        scale={[0.21, 0.21, 0.21]}
      />
      <group
        position={[-0.55, 0.3, -5.96]}
        rotation={[-3.12, -0.53, -2.94]}
        scale={[0.03, 0.03, 0.03]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder027_1.geometry}
          material={nodes.Cylinder027_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder027_2.geometry}
          material={nodes.Cylinder027_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder027_3.geometry}
          material={nodes.Cylinder027_3.material}
        />
      </group>
      <group position={[2.49, 0.46, 6.05]} rotation={[0.02, 0.02, 0.18]} scale={[0.02, 0.02, 0.02]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder026_1.geometry}
          material={nodes.Cylinder026_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder026_2.geometry}
          material={nodes.Cylinder026_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder026_3.geometry}
          material={nodes.Cylinder026_3.material}
        />
      </group>
      <group position={[2.65, 0.49, 6.12]} rotation={[0.01, 0.76, 0.02]} scale={[0.02, 0.02, 0.02]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder025_1.geometry}
          material={nodes.Cylinder025_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder025_2.geometry}
          material={nodes.Cylinder025_2.material}
        />
      </group>
      <group position={[2.57, 0.53, 5.84]} scale={[0.03, 0.03, 0.03]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder024_1.geometry}
          material={nodes.Cylinder024_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder024_2.geometry}
          material={nodes.Cylinder024_2.material}
        />
      </group>
      <group
        position={[-4.11, 0.83, -4.91]}
        rotation={[-0.06, 0.18, 0.16]}
        scale={[0.06, 0.06, 0.06]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder023_1.geometry}
          material={nodes.Cylinder023_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder023_2.geometry}
          material={nodes.Cylinder023_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder023_3.geometry}
          material={nodes.Cylinder023_3.material}
        />
      </group>
      <group
        position={[-3.96, 0.85, -4.73]}
        rotation={[0.09, 0.14, 0.07]}
        scale={[0.04, 0.04, 0.04]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder021_1.geometry}
          material={nodes.Cylinder021_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder021_2.geometry}
          material={nodes.Cylinder021_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder021_3.geometry}
          material={nodes.Cylinder021_3.material}
        />
      </group>
      <group
        position={[-0.22, 0.54, -4.4]}
        rotation={[0.03, -0.21, -0.05]}
        scale={[0.02, 0.02, 0.02]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder020_1.geometry}
          material={nodes.Cylinder020_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder020_2.geometry}
          material={nodes.Cylinder020_2.material}
        />
      </group>
      <group position={[-0.07, 0.48, -4.25]} rotation={[0.08, 0, -0.21]} scale={[0.03, 0.03, 0.03]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder019_1.geometry}
          material={nodes.Cylinder019_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder019_2.geometry}
          material={nodes.Cylinder019_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder019_3.geometry}
          material={nodes.Cylinder019_3.material}
        />
      </group>
      <group
        position={[-0.01, 0.44, -4.54]}
        rotation={[-0.03, -0.01, -0.27]}
        scale={[0.05, 0.05, 0.05]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder017_1.geometry}
          material={nodes.Cylinder017_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder017_2.geometry}
          material={nodes.Cylinder017_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder017_3.geometry}
          material={nodes.Cylinder017_3.material}
        />
      </group>
      <group position={[-6.6, 0.69, -4.48]} scale={[1.09, 1.09, 1.09]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube041_1.geometry}
          material={nodes.Cube041_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube041_2.geometry}
          material={nodes.Cube041_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube041_3.geometry}
          material={nodes.Cube041_3.material}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder014.geometry}
        material={nodes.Cylinder014.material}
        position={[2.68, 0.46, 5.89]}
        rotation={[0.02, -0.19, 0.28]}
        scale={[0.05, 0.05, 0.03]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder013.geometry}
        material={nodes.Cylinder013.material}
        position={[-5.48, 0.25, -5.77]}
        rotation={[-0.05, -0.3, 0.1]}
        scale={[0.05, 0.05, 0.03]}
      />
      <group position={[2.22, 0.23, 0.39]} rotation={[-0.09, 0.79, 0.3]} scale={[0.45, 0.45, 0.45]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere023_1.geometry}
          material={nodes.Icosphere023_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere023_2.geometry}
          material={nodes.Icosphere023_2.material}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder012.geometry}
        material={nodes.Cylinder012.material}
        position={[-4.62, 0.57, 3.78]}
        rotation={[-0.04, -0.49, -0.18]}
        scale={[0.05, 0.05, 0.03]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder011.geometry}
        material={nodes.Cylinder011.material}
        position={[5.51, 0.95, 2.55]}
        rotation={[-2.9, 0.13, -3.03]}
        scale={[0.02, 0.05, 0.04]}
      />
      <group position={[5.73, 0.52, -3.3]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube039_1.geometry}
          material={nodes.Cube039_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube039_2.geometry}
          material={nodes.Cube039_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube039_3.geometry}
          material={nodes.Cube039_3.material}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube038.geometry}
        material={nodes.Cube038.material}
        position={[-3.2, 0.74, -5.45]}
        rotation={[2.37, -0.27, -1.92]}
        scale={[0.15, 0.15, 0.15]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube037.geometry}
        material={nodes.Cube037.material}
        position={[-3.13, 0.65, -5.26]}
        rotation={[-1.23, -0.54, 0.99]}
        scale={[0.15, 0.15, 0.15]}
      />
      <group position={[0.37, 0.95, 5.02]} scale={[0.76, 0.76, 0.76]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere019_1.geometry}
          material={nodes.Icosphere019_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere019_2.geometry}
          material={nodes.Icosphere019_2.material}
        />
      </group>
      <group position={[-4.76, 1.7, 3.56]} rotation={[0.02, 0.79, -0.11]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube035_1.geometry}
          material={nodes.Cube035_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube035_2.geometry}
          material={nodes.Cube035_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube035_3.geometry}
          material={nodes.Cube035_3.material}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube034.geometry}
        material={nodes.Cube034.material}
        position={[1.57, -0.32, -0.78]}
        rotation={[-1.4, 0.04, -2.74]}
        scale={[0.29, 0.29, 0.29]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube033.geometry}
        material={nodes.Cube033.material}
        position={[1.18, -0.35, -0.76]}
        rotation={[-0.13, 1.42, -0.03]}
        scale={[0.29, 0.29, 0.29]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube032.geometry}
        material={nodes.Cube032.material}
        position={[-2.89, -0.37, 2.15]}
        rotation={[-0.92, -0.57, -3.11]}
        scale={[0.29, 0.29, 0.29]}
      />
      <group position={[-2.6, 0.52, 0.37]} scale={[2.4, 2.4, 2.4]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube031_1.geometry}
          material={nodes.Cube031_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube031_2.geometry}
          material={nodes.Cube031_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube031_3.geometry}
          material={nodes.Cube031_3.material}
        />
      </group>
      <group position={[5.43, 2.47, 2.31]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube030_1.geometry}
          material={nodes.Cube030_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube030_2.geometry}
          material={nodes.Cube030_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube030_3.geometry}
          material={nodes.Cube030_3.material}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder010.geometry}
        material={nodes.Cylinder010.material}
        position={[4.49, 0.17, -5.69]}
        rotation={[0, -Math.PI / 8, 0]}
        scale={[0.05, 0.07, 0.03]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder009.geometry}
        material={nodes.Cylinder009.material}
        position={[-4.32, 0.59, 6.03]}
        rotation={[0, -0.59, 0]}
        scale={[0.02, 0.06, 0.04]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder008.geometry}
        material={nodes.Cylinder008.material}
        position={[-3.32, 0.54, 6.95]}
        rotation={[0, -Math.PI / 8, 0]}
        scale={[0.05, 0.08, 0.03]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder007.geometry}
        material={nodes.Cylinder007.material}
        position={[4.86, 1.03, 3.66]}
        rotation={[-Math.PI, 0.71, -Math.PI]}
        scale={[0.02, 0.05, 0.04]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder006.geometry}
        material={nodes.Cylinder006.material}
        position={[-3.2, 0.83, -4.84]}
        rotation={[-0.09, -0.58, -0.09]}
        scale={[0.05, 0.06, 0.03]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder005.geometry}
        material={nodes.Cylinder005.material}
        position={[-3.15, 0.82, -4.71]}
        rotation={[-Math.PI, 0.71, -Math.PI]}
        scale={[0.02, 0.04, 0.04]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder003.geometry}
        material={nodes.Cylinder003.material}
        position={[-0.32, 0.41, -1.72]}
        rotation={[0.08, -0.37, 0.08]}
        scale={[0.05, 0.06, 0.03]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder002.geometry}
        material={nodes.Cylinder002.material}
        position={[-4.49, -0.03, 0.21]}
        rotation={[0.32, -0.19, 0.3]}
        scale={[0.05, 0.07, 0.03]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane003.geometry}
        material={materials.eau}
        position={[0, -0.17, -0.45]}
        scale={[8, 8, 3.34]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube029.geometry}
        material={nodes.Cube029.material}
        position={[-0.49, 0.26, -4.85]}
        rotation={[2.24, 0.83, 0.7]}
        scale={[0.2, 0.2, 0.2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube028.geometry}
        material={nodes.Cube028.material}
        position={[-0.72, 0.23, -5.27]}
        rotation={[-2.06, 0.98, 1.9]}
        scale={[0.31, 0.31, 0.31]}
      />
      <group position={[-0.34, 2.58, -5.05]} rotation={[-0.15, 0, 0.08]} scale={[0.53, 0.29, 0.53]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh.geometry}
          material={materials['feuille grand arbre']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_1.geometry}
          material={materials['Bois grand arbre']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube024.geometry}
        material={nodes.Cube024.material}
        position={[-6.62, 0.05, 1.03]}
        rotation={[1.77, -1.25, 0.29]}
        scale={[0.2, 0.2, 0.2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube023.geometry}
        material={nodes.Cube023.material}
        position={[-5.99, -0.1, 0.28]}
        rotation={[0.06, 0.08, -0.22]}
        scale={[0.1, 0.1, 0.1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube022.geometry}
        material={nodes.Cube022.material}
        position={[-6.03, -0.09, 0.99]}
        rotation={[1.13, 0.24, 0.38]}
        scale={[0.6, 0.6, 0.6]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube021.geometry}
        material={nodes.Cube021.material}
        position={[-5.7, 0.16, -2.94]}
        rotation={[0.79, -0.24, 0.21]}
        scale={[0.62, 0.62, 0.62]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube020.geometry}
        material={nodes.Cube020.material}
        position={[3.19, 0.61, 5.7]}
        rotation={[-1, 0.01, -2.05]}
        scale={[0.51, 0.51, 0.51]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere012.geometry}
        material={nodes.Icosphere012.material}
        position={[4.1, 0.16, -6.22]}
        rotation={[-0.1, -0.01, -0.22]}
        scale={[0.67, 0.67, 0.67]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube019.geometry}
        material={nodes.Cube019.material}
        position={[-5.31, 0.04, -1]}
        rotation={[2.33, -0.49, -0.37]}
        scale={[0.12, 0.12, 0.12]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube018.geometry}
        material={nodes.Cube018.material}
        position={[-4.73, 0.07, -1.24]}
        rotation={[-2, -0.23, 2.32]}
        scale={[0.62, 0.62, 0.62]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere011.geometry}
        material={nodes.Icosphere011.material}
        position={[-4.95, -0.15, -0.51]}
        rotation={[3.01, -1.4, 1.68]}
        scale={[0.83, 0.83, 0.83]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere010.geometry}
        material={nodes.Icosphere010.material}
        position={[-3.93, 0.63, 5.47]}
        rotation={[-0.95, 0.56, 2.86]}
        scale={[0.35, 0.35, 0.35]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere009.geometry}
        material={nodes.Icosphere009.material}
        position={[-4.14, 0.69, 5.82]}
        scale={[0.24, 0.24, 0.24]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube017.geometry}
        material={nodes.Cube017.material}
        position={[-3.64, 0.49, 6.16]}
        rotation={[1.6, -0.01, 2.05]}
        scale={[0.52, 0.52, 0.52]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere008.geometry}
        material={nodes.Icosphere008.material}
        position={[-2.51, 0.08, 6.16]}
        rotation={[-0.45, 0.44, -1.3]}
        scale={[1.03, 1.03, 1.03]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere007.geometry}
        material={nodes.Icosphere007.material}
        position={[5.57, 0.49, 4.99]}
        scale={[0.48, 0.48, 0.48]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube016.geometry}
        material={nodes.Cube016.material}
        position={[6.92, 0.26, 4.9]}
        scale={[0.16, 0.16, 0.16]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube015.geometry}
        material={nodes.Cube015.material}
        position={[6.23, 0.29, 5.19]}
        rotation={[2.01, -0.8, 2.79]}
        scale={[0.54, 0.54, 0.54]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube014.geometry}
        material={nodes.Cube014.material}
        position={[0.55, -0.11, -5.26]}
        rotation={[-1.66, -0.95, -1.09]}
        scale={[0.2, 0.2, 0.2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube013.geometry}
        material={nodes.Cube013.material}
        position={[0.79, -0.03, -5.22]}
        scale={[0.16, 0.16, 0.16]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube012.geometry}
        material={nodes.Cube012.material}
        position={[-1.21, 0.02, -5.86]}
        rotation={[2.35, 0.37, -2.05]}
        scale={[0.62, 0.62, 0.62]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube011.geometry}
        material={nodes.Cube011.material}
        position={[6.81, 0.1, 4.37]}
        rotation={[0.81, -0.16, 0.25]}
        scale={[0.54, 0.54, 0.54]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube010.geometry}
        material={nodes.Cube010.material}
        position={[0.42, -0.37, -4.81]}
        rotation={[-1.98, -0.29, -0.32]}
        scale={[0.62, 0.62, 0.62]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube009.geometry}
        material={nodes.Cube009.material}
        position={[-0.57, -0.2, -0.4]}
        scale={[0.31, 0.31, 0.31]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube008.geometry}
        material={nodes.Cube008.material}
        position={[-1.1, -0.07, 0.08]}
        rotation={[-1.7, -0.38, -1.88]}
        scale={[0.67, 0.67, 0.67]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube007.geometry}
        material={nodes.Cube007.material}
        position={[-1.8, -0.43, 0.77]}
        scale={[0.53, 0.53, 0.53]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere005.geometry}
        material={nodes.Icosphere005.material}
        position={[3.64, -0.32, -0.5]}
        rotation={[-0.16, 0.44, -2.96]}
        scale={[0.55, 0.55, 0.55]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere004.geometry}
        material={nodes.Icosphere004.material}
        position={[4.18, -0.21, -0.55]}
        rotation={[0.19, -0.74, 0]}
        scale={[0.83, 0.83, 0.83]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={nodes.Cube.material}
        position={[-3.56, 2.06, -4.43]}
        scale={[0.39, 0.39, 0.39]}
      />
      <group position={[0.2, 0.01, -0.24]} scale={[8, 8, 8]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001_1.geometry}
          material={materials['herbe ground']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001_2.geometry}
          material={materials.sable}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/glb/nature/the-river.glb');
