/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function TieFighter(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF('/glb/sci-fi/tie-fighter-draco-256.glb');
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Mesh_0002.geometry} material={nodes.Mesh_0002.material} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_1001.geometry} material={nodes.Mesh_1001.material} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_2001.geometry} material={nodes.Mesh_2001.material} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_3.geometry} material={nodes.Mesh_3.material} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_4.geometry} material={materials.RedEngineGlow} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_5.geometry} material={nodes.Mesh_5.material} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_6.geometry} material={nodes.Mesh_6.material} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_12.geometry} material={nodes.Mesh_12.material} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_10.geometry} material={nodes.Mesh_10.material} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_11.geometry} material={materials.ScratchedMetalOrange} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_7.geometry} material={nodes.Mesh_7.material} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_8.geometry} material={nodes.Mesh_8.material} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_9.geometry} material={nodes.Mesh_9.material} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_13.geometry} material={nodes.Mesh_13.material} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_14.geometry} material={nodes.Mesh_14.material} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_15.geometry} material={nodes.Mesh_15.material} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_16.geometry} material={nodes.Mesh_16.material} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_17.geometry} material={nodes.Mesh_17.material} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_18.geometry} material={materials.ReflectiveGlass} />
    </group>
  );
}

useGLTF.preload('/glb/sci-fi/tie-fighter-draco-256.glb');
