/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

export default function XWing(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('/glb/sci-fi/x-wing-animated.glb');
  // const { actions } = useAnimations(animations, group);

  // console.log(actions['Take 01']);
  //
  // useEffect(() => {
  //   if (actions) {
  //     actions['Take 01'].play();
  //   }
  // });

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0.31, -2.14, 0.46]} rotation={[Math.PI / 2, 0, 0]} scale={[0.07, 0.07, 0.07]}>
          <mesh castShadow receiveShadow geometry={nodes.Circle_0.geometry} material={nodes.Circle_0.material} />
        </group>
        <group position={[0.31, -2.14, 0.46]} rotation={[Math.PI / 2, 0, 0.13]} scale={[0.16, 0.15, 0.15]}>
          <mesh castShadow receiveShadow geometry={nodes.Circle001_0.geometry} material={nodes.Circle001_0.material} />
        </group>
        <group position={[0.59, -2.16, 0.69]} rotation={[Math.PI / 2, 0, 0]} scale={[0.01, 0.01, 0.01]}>
          <mesh castShadow receiveShadow geometry={nodes.Circle002_0.geometry} material={materials.BakedCycles} />
        </group>
        <group position={[0, -0.93, 0.46]} rotation={[0, 0, 0]} scale={[0.27, 0.27, 0.27]}>
          <mesh castShadow receiveShadow geometry={nodes.Cube_1.geometry} material={materials.GLASS} />
          <mesh castShadow receiveShadow geometry={nodes.Cube_0.geometry} material={nodes.Cube_0.material} />
        </group>
        <group position={[0.31, -2.14, 0.46]} rotation={[0, 0, 0]}>
          <mesh castShadow receiveShadow geometry={nodes.Plane_0.geometry} material={nodes.Plane_0.material} />
        </group>
        <group position={[0.31, -2.14, 0.46]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh castShadow receiveShadow geometry={nodes.Plane001_0.geometry} material={nodes.Plane001_0.material} />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/glb/sci-fi/x-wing-animated.glb');
