/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

export default function XWing(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF('/glb/sci-fi/x-wing-2-draco-512.glb');

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_11001.geometry}
          material={materials['lambert2SG.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_12001.geometry}
          material={materials.lambert3SG}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_13.geometry}
          material={materials.lambert4SG}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_5001.geometry}
          material={nodes.Mesh_5001.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_0001.geometry}
          material={materials['blinn2SG.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_14.geometry}
          material={materials.lambert6SG}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_8001.geometry}
          material={nodes.Mesh_8001.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_2001.geometry}
          material={nodes.Mesh_2001.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_6001.geometry}
          material={nodes.Mesh_6001.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_1001.geometry}
          material={nodes.Mesh_1001.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_10001.geometry}
          material={nodes.Mesh_10001.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_9001.geometry}
          material={nodes.Mesh_9001.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_15.geometry}
          material={materials['lambert7SG.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_3001.geometry}
          material={materials.blinn5SG}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_7001.geometry}
          material={nodes.Mesh_7001.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_4001.geometry}
          material={nodes.Mesh_4001.material}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/glb/sci-fi/x-wing-2-draco-512.glb');
